# Inherit from omni
$(call inherit-product, device/infinix/X6885/omni_X6885.mk)

# OrangeFox Configuration
FOX_VERSION := R12.1
FOX_BUILD_TYPE := Unofficial
OF_MAINTAINER := Anang

# Features
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_NO_MIUI_PATCH := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASHING := 1

# Display
OF_SCREEN_H := 2400
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_USE_GREEN_LED := 0

# Security / Tools
OF_SKIP_ORANGEFOX_PROCESS := 1
OF_ADVANCED_SECURITY := 1
FOX_DELETE_AROMAFM := 1

PRODUCT_DEVICE := X6885
PRODUCT_NAME := fox_X6885
